# Generated by Django 3.2.4 on 2022-08-30 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0005_postmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='upvotes',
            field=models.ManyToManyField(related_name='blocpost_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
