# Generated by Django 3.2.4 on 2022-08-30 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220830_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='upvotes',
        ),
    ]
